### ISSUE TITLE
Why parameters from codes and those of the paper are quite different?what is better?

### ISSUE THREAD

**Issue by baimin1** [yenchenlin/DeepLearningFlappyBird#22]
Why parameters (and network struct) from codes and those of the paper are quite different?what is better? Thank you

boolings are all commented, why ?  Such as
#h_pool2 = max_pool_2x2(h_conv2)

**Comment by yenchenlin** [comment]
Hello, I will update the code recently!
However, this project did not accurately follow the DQN paper, so I did it only because it work.
