### ISSUE TITLE
Why do the program only use two state?

### ISSUE THREAD

**Issue by guotong1988** [yenchenlin/DeepLearningFlappyBird#33]
I read from [here](https://github.com/yenchenlin/DeepLearningFlappyBird/blob/master/deep_q_network.py#L156-L176).
Why do the program only use the current state and the next state?
Why only using the two state can work?
Thank you @yenchenlin

**Comment by ColdCodeCool** [comment]
@guotong1988  I think you should learn the very basic concept of reinforcement learning. It is basically a dynamic program, the state changes from time to time. You'd better learn Markov Decision Process and Bellman Equation  first.

**Comment by guotong1988** [comment]
the state changes from time to time
thank you
could you please have a look at my another question? thx!
the question is also in the issues

**Comment by guotong1988** [comment]
反过来想，为什么不只用1个state呢，而用了2个state

**Comment by ColdCodeCool** [comment]
@guotong1988  no, you cannot only use one state, since intuitively you must communicate with the environment by behaving to learn a lesson. Once your action done, you are in another state, and you get reward or punishment from the environment, thus you can learn something.

**Comment by ColdCodeCool** [comment]
@guotong1988  for comprehensive understanding, you should learn mdp theory first.

**Comment by guotong1988** [comment]
关键这两个state是紧挨着的，有反馈也不是立即有效啊，
就是说第二个state有情况，是前若干步决定的啊

**Comment by ColdCodeCool** [comment]
@guotong1988  like I said, you really need learn mdp first. Markov property informs the current state captures all relevant information from the history. Thus the future state only depends on the current state. In mathematical forms, P[s_{t+1}|s_{t}] = P[s_{t+1}|s_1,...,s_t].

**Comment by guotong1988** [comment]
The answer: One state contains 4 frame.

**Comment by guotong1988** [comment]
The answer: One state contains 4 frame.
