### ISSUE TITLE
are those calculations right??

### ISSUE THREAD

**Issue by jbsgbmr** [yenchenlin/DeepLearningFlappyBird#39]
In the figure, 
I wonder that your math things are valid

I mean, 
1) input 80 x 80 x 4 -- conv. w/ 8 x 8 x 4 x 32, stride 4 --> output 19 x 19 x 32 
(because (80 - 8) / 4 + 1) => your result was 20 x 20 x 32
2) input 10 x 10 x 32 -- conv. w/ 4 x 4 x32 x 64, stride 2 ---> output 4 x 4 x 64
(because (10 - 4) / 2 + 1) => your result was 5 x 5 x 64

3) and...  
input 3 x 3 x 64 -- conv. w/ 3 x 3 x64 x 64 --> your result was 3 x 3 x 64 (is this possible?)

am I wrong? 
Since I am a newbie on this area, if I misunderstood, please teach me.

**Comment by wenjiebit** [comment]
because padding = ‘SAME’

**Comment by yenchenlin** [comment]
Thanks @wenjiebit :)
