### ISSUE TITLE
Stack last 4 frames ?

### ISSUE THREAD

**Issue by BoyuanYan** [yenchenlin/DeepLearningFlappyBird#48]
It seems that these 4 frames comes are the same on https://github.com/yenchenlin/DeepLearningFlappyBird/blob/master/deep_q_network.py#L102

**Comment by patrick-llgc** [comment]
@BoyuanYan that is only the initialization. See [here](https://github.com/yenchenlin/DeepLearningFlappyBird/blob/master/deep_q_network.py#L143) on how it is updated.

**Comment by BoyuanYan** [comment]
> @BoyuanYan that is only the initialization. See [here](https://github.com/yenchenlin/DeepLearningFlappyBird/blob/master/deep_q_network.py#L143) on how it is updated.

Thanks :)

**Comment by JerryRC** [comment]
我特么看不懂。

发送自 Windows 10 版邮件应用

发件人: Patrick Liu
发送时间: 2019年1月24日 7:06
收件人: yenchenlin/DeepLearningFlappyBird
抄送: Subscribed
主题: Re: [yenchenlin/DeepLearningFlappyBird] Stack last 4 frames ? (#48)

@BoyuanYan that is only the initialization. See here on how it is updated.
